os: linux
dist: xenial
language: erlang
jobs:
  include:
    - name: OTP/23.0
      otp_release: 23.0
      script:
        - make tests
        - make dialyze
    - name: OTP/22.3
      otp_release: 22.3
      script:
        - make tests
    - name: OTP/21.3
      otp_release: 21.3
      script:
        - make tests
